[package]
name = "queue_consumer"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json.workspace = true
serde.workspace = true
rdkafka.workspace = true
tokio-stream.workspace = true
anyhow.workspace = true
