[package]
name = "demo"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic.workspace = true
hdf5.workspace = true
log.workspace = true
env_logger.workspace = true
anyhow.workspace = true
proto.workspace = true
tokio.workspace = true
ndarray.workspace = true
